//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCallLog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCL_Sub_Category
    {
        public string CATEGORY_ID { get; set; }
        public string SUB_CATEGORY_ID { get; set; }
        public string SUB_CATEGORY_DESC { get; set; }
        public string Step1 { get; set; }
        public string Step2 { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public int ID { get; set; }
        public string Status { get; set; }
    }
}
