//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCallLog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCL_ComplaintImages
    {
        public int ID { get; set; }
        public Nullable<int> Complaint_ID { get; set; }
        public string AttachmentName { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public byte[] AttachmentBinary { get; set; }
        public string AttachmentRealName { get; set; }
        public string Extension { get; set; }
        public string Device { get; set; }
        public string GeneratedAttachmentName { get; set; }
        public string Complaint_ReferenceNo { get; set; }
    }
}
