//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCallLog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCL_Login
    {
        public int ID { get; set; }
        public int CID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string type { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> cdate { get; set; }
        public string Flag { get; set; }
        public Nullable<System.DateTime> SubscriptionEndDate { get; set; }
    }
}
