//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCallLog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCL_WorkOrder_Details
    {
        public int WODID { get; set; }
        public int WOID { get; set; }
        public string WO_REFERENCE { get; set; }
        public System.DateTime WO_DATE { get; set; }
        public string JC_REFERENCE { get; set; }
        public Nullable<System.DateTime> COMP_DATE { get; set; }
        public int COMPANY_ID { get; set; }
        public int COMPLAINT_ID { get; set; }
        public int USER_ID { get; set; }
        public string DEPARTMENT { get; set; }
        public string CATEGORY { get; set; }
        public string SUB_CATEGORY { get; set; }
        public string ADDRESS { get; set; }
        public string COMP_STATUS { get; set; }
        public string COMP_COMMENTS { get; set; }
        public Nullable<int> FLAG { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<int> MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string START_DATE { get; set; }
        public string END_DATE { get; set; }
        public string SERVICE_HOURS { get; set; }
    }
}
