//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCallLog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCL_UserScreens
    {
        public int ID { get; set; }
        public string ScreenName { get; set; }
        public string Description { get; set; }
        public Nullable<int> CompanyID { get; set; }
    }
}
